### ISSUE TITLE
How to Run ?

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/caps-examples#2]
I have downloaded the project and opened it with eclipse, however i can not run the scala class as scala application ??

**Comment by pstutz** [comment]
What happens when you try to run `HelloCypher` in Eclipse?

**Comment by HADDADENICAR** [comment]
after i click in tun button  i get this : 

      [INFO] Scanning for projects...
      [INFO] ------------------------------------------------------------------------
      [INFO] BUILD FAILURE
      [INFO] ------------------------------------------------------------------------
      [INFO] Total time: 0.474 s
     [INFO] Finished at: 2018-07-16T14:02:59+02:00
     [INFO] Final Memory: 5M/61M
      [INFO] ------------------------------------------------------------------------
     [ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
     [ERROR] 
     [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
     [ERROR] Re-run Maven using the -X switch to enable full debug logging.
     [ERROR] 
     [ERROR] For more information about the errors and possible solutions, please read the following articles:
     [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

before that i just run **maven install**

**Comment by pstutz** [comment]
Did you use the [Scala-IDE](http://scala-ide.org) version of Eclipse? Sorry, we currently don't document IDE setups.

**Comment by pstutz** [comment]
Alternatively you could probably install the Scala plugin for Eclipse.

**Comment by HADDADENICAR** [comment]
No I use Eclipse Oxygen

**Comment by pstutz** [comment]
From Maven you can run with `mvn scala:run -DmainClass=org.opencypher.example.HelloCypher`
If that works then I suspect that it's a problem with the IDE setup.

**Comment by pstutz** [comment]
Maybe [this article](http://scala-ide.org/docs/tutorials/m2eclipse/) helps with the IDE setup?

**Comment by HADDADENICAR** [comment]
it works with `mvn scala:run -DmainClass=org.opencypher.example.HelloCypher`. however what i really need of the project is  **the Creation of  graph from the dataframe and storing it in Neo4j**,so basically i need  to run the spark [DataFrameInputExample](https://github.com/opencypher/cypher-for-apache-spark/blob/master/spark-cypher-examples/src/main/scala/org/opencypher/spark/examples/DataFrameInputExample.scala)

i tried to inspire from your previous cmd , i run in ***cypher-for-apache-spark-folder*** this cmd : 
    
    mvn scala:run -DmainClass=spark-cypher-examples.src.main.scala.org.opencypher.spark.examples.DataFrameInputExample

but i get this exception : 
    
          [INFO] --- scala-maven-plugin:3.2.1:run (default-cli) @ okapi ---

          java.lang.ClassNotFoundException: spark-cypher-  examples.src.main.scala.org.opencypher.spark.examples.DataFrameInputExample
          at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
          at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
          at scala_maven_executions.MainHelper.runMain(MainHelper.java:154)
          at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
          [INFO] ------------------------------------------------------------------------
          [INFO] Reactor Summary:
          [INFO]
          [INFO] Okapi - openCypher query compilation API and pipeline 1.0.0-SNAPSHOT FAILURE [ 11.993 s]
    
so how to run **DataFrameInputExample** ?

**Comment by pstutz** [comment]
Try copying the code to your local examples project. The examples module of CAPS is not part of the dependencies of this example project.

**Comment by pstutz** [comment]
Did the IDE setup still not work with both the Scala and m2eclipse-scala plugins? What issues did you encounter?

**Comment by HADDADENICAR** [comment]
> Try copying the code to your local examples project. 

what do you mean ?

> The examples module of CAPS is not part of the dependencies of this example project.

 yes for the Input Dataframe example i used the (Cypher for Apache Spark ) project not this .may be i need to open a new issue there .

> Did the IDE setup still not work with both the Scala and m2eclipse-scala plugins? 

yes, what i did is : 
* import the project as a maven project
but i can't : 
* run the scala classes ( apparently it requires a **main** function to run)
* add a new scala class (eclipse tell me that's not a scala project)

**Comment by pstutz** [comment]
About project setup: did you install the m2eclipse-scala plugin that I linked to above?

**Comment by pstutz** [comment]
> > Try copying the code to your local examples project.

> what do you mean ?

The code you reference is not present in your project. An easy way to get that code into your project is to copy the example code.

Edit: Ah, sorry, so this is an independent issue with a different setup. Probably best to create a new issue.

**Comment by pstutz** [comment]
I followed these steps to get `HelloCypher` to run in Eclipse:
- [Download & install Eclipse Oxygen](http://www.eclipse.org/oxygen/), `Eclipse IDE for Java EE Developers` edition
- [Install Scala plugin for Eclipse](http://download.scala-ide.org/sdk/lithium/e47/scala212/stable/site)
- [Install `Maven Integration for Scala IDE`](http://alchim31.free.fr/m2e-scala/update-site)
- Import project as `Existing Maven Projects`
- Right click on `Project`, `Properties`, `Scala Compiler`, set `Scala Installation` to `Fixed Scala Installation 2.11.11 (built-in)`
- Right click on project, `Run As`, `Maven build`
- Right click `HelloCypher`, `Run As`, `Scala Application`

Without the `Maven build` step I got an error that the main class was not found, which is not good at all. I suspect that both plugins are insufficiently maintained and would recommend using IntelliJ instead.

**Comment by HADDADENICAR** [comment]
Thanks @pstutz actually i did as you suggested however the run didn't succeed for me  for this reason : 

    Exception in thread "main" java.lang.NumberFormatException: Not a version: 9

what is the Java -version you use ?

**Comment by pstutz** [comment]
You probably have to switch the project JDK to version `8`/`1.8`

**Comment by HADDADENICAR** [comment]
it is weird because i have a java 1.8 jdk !!

and 

          mvn scala:run -DmainClass=org.opencypher.example.HelloCypher
succeed previously

**Comment by pstutz** [comment]
That's weird indeed, it works for me with version `1.8`.

**Comment by HADDADENICAR** [comment]
Ok , i justed downloaded Intellij IDEA and i m able to run it, but with its **Terminal**

**Comment by HADDADENICAR** [comment]
Ok , i justed downloaded Intellij IDEA and i m able to run it, but with its **Terminal**

**Comment by HADDADENICAR** [comment]
Since i solved this problem with **Intellij IDEA**, i put this comment for who needs help :
IntelliJ IDEA does the `mvn clean install` automatically so no need to a terminal.
the only thing needed to run caps is a scala plugin , then you can open your project on the ide and run your scala class as "Application".
IntelliJ IDEA can run caps on linux and windows too.
hope that would help a future "Hello world"
